<?php 
// Include the connection file 
require 'config.php';  

// Function to display the privacy policy content 
function display_privacy_policy() { 
    echo '<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Privacy Policy - BookMyLawyer</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                line-height: 1.6;
                margin: 0;
                padding: 0;
                background-color: #f4f4f4;
            }
            .container {
                max-width: 800px;
                margin: 50px auto;
                padding: 20px;
                background: #fff;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
            }
            h1, h2, h3 {
                color: #333;
            }
            p {
                color: #555;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Privacy Policy</h1>
            <p>Welcome to BookMyLawyer, a platform designed to connect clients with professional lawyers for various legal needs including civil, criminal, divorce, family, and corporate cases. This Privacy Policy explains how we collect, use, and protect your personal information when you use our service.</p>
            
            <h2>Interpretation and Definitions</h2>
            <h3>Interpretation</h3>
            <p>The words with initial letters capitalized have meanings defined under the following conditions. These definitions have the same meaning whether in singular or plural form.</p>
            
            <h3>Definitions</h3>
            <ul>
                <li><strong>Account:</strong> A unique account created for You to access our Service.</li>
                <li><strong>Application:</strong> Refers to BookMyLawyer, the software provided by the Company.</li>
                <li><strong>Company:</strong> Refers to BookMyLawyer.</li>
                <li><strong>Country:</strong> Tamil Nadu, India.</li>
                <li><strong>Device:</strong> Any device capable of accessing the Service, such as a computer, cellphone, or tablet.</li>
                <li><strong>Personal Data:</strong> Any information relating to an identified or identifiable individual.</li>
                <li><strong>Service:</strong> The BookMyLawyer Application.</li>
                <li><strong>Service Provider:</strong> Any person or entity processing data on behalf of the Company.</li>
                <li><strong>Usage Data:</strong> Data collected automatically, generated by the use of the Service or from the Service infrastructure.</li>
                <li><strong>You:</strong> The individual or entity accessing or using the Service.</li>
            </ul>
            
            <h2>Collecting and Using Your Personal Data</h2>
            <h3>Types of Data Collected</h3>
            
            <h4>Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. This may include:</p>
            <ul>
                <li>Full Name</li>
                <li>Email address</li>
                <li>Password</li>
                <li>Phone number</li>
                <li>Case details (when booking a lawyer)</li>
            </ul>
            
            <h4>Usage Data</h4>
            <p>Usage Data is collected automatically when using BookMyLawyer. This may include your device’s IP address, browser type and version, the pages of our Service you view (such as lawyer profiles, bookings, or payment history), the date and time of your visit, time spent on those pages, unique device identifiers, and diagnostic data.</p>
            
            <h2>Sharing Your Personal Data</h2>
            <ul>
                <li><strong>With Service Providers:</strong> To monitor and analyze the use of our Service and improve user experience.</li>
                <li><strong>For Business Transfers:</strong> During mergers, sales, or acquisitions.</li>
                <li><strong>With Affiliates:</strong> Including our parent company and other subsidiaries under common control.</li>
                <li><strong>With Business Partners:</strong> To offer related services such as case consultation or legal document support.</li>
                <li><strong>With Lawyers:</strong> To provide them with the necessary details to serve your booking request.</li>
                <li><strong>With Your Consent:</strong> For any other purpose with your explicit consent.</li>
            </ul>
            
            <h2>Retention of Your Personal Data</h2>
            <p>We will retain Your Personal Data only for as long as necessary to fulfill the purposes outlined in this Privacy Policy, and to comply with legal obligations. Data related to your bookings and case interactions may be retained to support continuity of service and for compliance with legal regulations.</p>
            
            <h2>Security of Your Personal Data</h2>
            <p>We use commercially acceptable methods to safeguard your Personal Data. However, please note that no method of transmission over the Internet or electronic storage is 100% secure.</p>
            
            <h2>Children\'s Privacy</h2>
            <p>Our Service does not target individuals under 18. We do not knowingly collect data from this age group. If you are a parent or guardian and become aware of such data collection, please contact us.</p>
            
            <h2>Changes to this Privacy Policy</h2>
            <p>We may update this Privacy Policy and will notify you of any changes by posting the new policy on this page. Please review the policy periodically for updates.</p>
            
            <h2>Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:252434018.sclas@saveetha.com">252434018.sclas@saveetha.com</a>.</p>
            
            <p>© 2025 BookMyLawyer. All rights reserved.</p>
        </div>
    </body>
    </html>'; 
}  

display_privacy_policy(); 
?>
